Repository Another-Glass/Assignment2_Team, pull requests merged in 2021-11, with the labels that each got.

#6 [chore]: RDS MySQL DB 연결
  src/configs/db.js
  src/models/autoIdSetter.js
  src/models/index.js
  src/models/item.js
  src/models/menu.js
  src/models/post.js
  src/models/tag.js
  src/models/user.js
  src/package.json
  src/services/menuService.js
  src/services/postService.js
  src/services/userService.js
Labels: 🔥 Feat, 🧑🏻‍💻 동훈, ⭐️ Chore

#10 [Feat] 메뉴 생성 테스트 코드 작성
  src/package.json
  src/test/Menu/createMenu.test.js
  src/test/User/signin.test.js
  src/test/User/signup.test.js
Labels: 🔥 Feat, 🧑🏻‍💻 상수

#11 [feat]: 메뉴 수정 테스트 코드 작성
  src/controllers/postController.js
  src/test/Menu/putMenu.test.js
Labels: 🔥 Feat, 🧑🏻‍💻 상수

#12 [feat]: 메뉴 삭제 테스트 코드 작성
  src/test/Menu/deleteMenu.test.js
Labels: 🔥 Feat, 🧑🏻‍💻 상수

#14 [Fix]:사용자, 메뉴, 태그, 아이템 api 수정
  src/app.js
  src/controllers/itemController.js
  src/controllers/menuController.js
  src/controllers/tagController.js
  src/controllers/userController.js
  src/globals/responseMessage.js
  src/globals/routes.js
  src/globals/statusCode.js
  src/libs/jwt.js
  src/middlewares/auth.js
  src/models/index.js
  src/models/tag.js
  src/routes/menuRouter.js
  src/routes/tagRouter.js
  src/routes/tokenRouter.js
  src/services/itemService.js
  src/services/menuService.js
  src/services/tagService.js
  src/services/userService.js
  src/utils/errors/menuError.js
Labels: 🔥 Feat, 🧑🏻‍💻 준호

#13 [feat]: 메뉴 조회 테스트 코드 작성
  src/test/Menu/getMenu.test.js
Labels: 🔥 Feat, 🧑🏻‍💻 상수

#17 [feat]: 메뉴 전체 조회 테스트 코드 작성
  src/test/Menu/getMenuList.test.js
Labels: 🔥 Feat, 🧑🏻‍💻 상수

#16 [feat]: DB Service 파트 구현
  src/models/menu.js
  src/models/tag.js
  src/services/itemService.js
  src/services/menuService.js
  src/services/tagService.js
  src/services/userService.js
Labels: 🔥 Feat, 🧑🏻‍💻 동훈

#18 [feat]: 태그 생성 테스트 코드 추가
  src/test/Tag/postTag.test.js
Labels: 🔥 Feat, 🧑🏻‍💻 상수

#19 [feat]: 태그 수정 테스트 코드 작성
  src/test/Tag/putTag.test.js
Labels: 🔥 Feat, 🧑🏻‍💻 상수

#21 [feat]: 태그 삭제 테스트 코드 작성
  src/test/Tag/deleteTag.test.js
Labels: 🔥 Feat, 🧑🏻‍💻 상수

#26 [feat]: 태그 조회 테스트 코드 작성
  src/test/Tag/getTag.test.js
Labels: 🔥 Feat, 🧑🏻‍💻 상수

#30 [fix]: 테스트 후 버그 수정
  package-lock.json
  src/app.js
  src/controllers/itemController.js
  src/controllers/menuController.js
  src/controllers/tagController.js
  src/controllers/userController.js
  src/globals/responseMessage.js
  src/libs/jwt.js
  src/middlewares/auth.js
  src/routes/menuRouter.js
  src/routes/tagRouter.js
  src/services/menuService.js
  src/services/tagService.js
  src/services/userService.js
  src/utils/errors/menuError.js
  src/utils/errors/tagError.js
Labels: 🛠 Fix, 🧑🏻‍💻 2차 과제 팀

#7 [feat] 테스트 코드 작성
  package-lock.json
  src/.babelrc
  src/.gitignore
  src/package.json
  src/routes/userRouter.js
  src/test/Menu/createMenu.test.js
  src/test/Menu/deleteMenu.test.js
  src/test/Menu/getMenu.test.js
  src/test/Menu/getMenuList.test.js
  src/test/Menu/putMenu.test.js
  src/test/Tag/deleteTag.test.js
  src/test/Tag/getTag.test.js
  src/test/Tag/postTag.test.js
  src/test/Tag/putTag.test.js
  src/test/User/signin.test.js
  src/test/User/signup.test.js
Labels: 🔥 Feat, 🧑🏻‍💻 상수

#38 [fix]: 유저 회원가입 테스트 코드 수정
  src/controllers/userController.js
  src/test/Menu/createMenu.test.js
  src/test/Menu/deleteMenu.test.js
  src/test/Menu/getMenu.test.js
  src/test/Menu/getMenuList.test.js
  src/test/Menu/putMenu.test.js
  src/test/Tag/deleteTag.test.js
  src/test/Tag/getTag.test.js
  src/test/Tag/postTag.test.js
  src/test/Tag/putTag.test.js
  src/test/User/signin.test.js
  src/test/User/signup.test.js
Labels: 🛠 Fix, 🧑🏻‍💻 상수

#39 [fix]: 사용자 로그인 테스트 코드 수정
  src/test/Token/postToken.test.js
  src/test/User/signin.test.js
Labels: 🛠 Fix, 🧑🏻‍💻 상수

#40 [fix]: 메뉴 추가 테스트 코드 수정
  src/test/Menu/createMenu.test.js
Labels: 🛠 Fix, 🧑🏻‍💻 상수

#41 [fix]: 전체 메뉴 조회 테스트 코드 수정
  src/test/Menu/getMenuList.test.js
Labels: 🛠 Fix, 🧑🏻‍💻 상수

#42 [fix]: 메뉴 삭제 테스트 코드 수정
  src/test/Menu/deleteMenu.test.js
Labels: 🛠 Fix, 🧑🏻‍💻 상수

#44 [fix]: 메뉴 수정 테스트 코드 수정
  src/test/Menu/putMenu.test.js
Labels: 🛠 Fix, 🧑🏻‍💻 상수

#45 [fix]: 메뉴 상세조회 테스트 코드 수정
  src/test/Menu/getMenu.test.js
Labels: 🛠 Fix, 🧑🏻‍💻 상수

#46 [fix]: 태그 생성 테스트 코드 수정
  src/test/Tag/postTag.test.js
Labels: 🛠 Fix, 🧑🏻‍💻 상수

#43 [Comment]: DB 서비스 javadoc 주석 추가
  src/models/index.js
  src/services/itemService.js
  src/services/menuService.js
  src/services/tagService.js
  src/services/userService.js
Labels: 🧑🏻‍💻 동훈

#47 [fix]: 코드 정리 및 버그수정
  src/app.js
  src/controllers/itemController.js
  src/controllers/menuController.js
  src/controllers/tagController.js
  src/controllers/userController.js
  src/globals/responseMessage.js
  src/libs/encryption.js
  src/libs/jwt.js
  src/middlewares/auth.js
  src/models/index.js
  src/routes/index.js
  src/routes/menuRouter.js
  src/routes/tokenRouter.js
  src/routes/userRouter.js
  src/services/itemService.js
  src/services/tagService.js
  src/utils/errors/commonError.js
  src/utils/errors/menuError.js
Labels: 🛠 Fix, 🧑🏻‍💻 2차 과제 팀

#48 [fix]: 태그 수정, 삭제 테스트 코드 수정
  src/test/Tag/deleteTag.test.js
  src/test/Tag/putTag.test.js
Labels: 🛠 Fix, 🧑🏻‍💻 상수

#49 [fix]: 테스트 코드 2차 수정
  src/controllers/userController.js
  src/test/Menu/createMenu.test.js
  src/test/Menu/deleteMenu.test.js
  src/test/Menu/getMenu.test.js
  src/test/Menu/getMenuList.test.js
  src/test/Menu/putMenu.test.js
  src/test/Tag/deleteTag.test.js
  src/test/Tag/getTag.test.js
  src/test/Tag/postTag.test.js
  src/test/Tag/putTag.test.js
  src/test/Token/postToken.test.js
  src/test/User/signup.test.js
Labels: 🛠 Fix, 🧑🏻‍💻 상수

#50 [fix]: 버그 수정 및 에러처리 추가
  src/controllers/menuController.js
  src/controllers/tagController.js
  src/routes/menuRouter.js
  src/services/tagService.js
Labels: 🛠 Fix, 🧑🏻‍💻 2차 과제 팀

#51 [fix]: 버그 수정 3차
  src/controllers/itemController.js
  src/controllers/menuController.js
  src/controllers/tagController.js
Labels: 🛠 Fix, 🧑🏻‍💻 2차 과제 팀

#53 [docs]: README 2차 과제 작성
  README.md
Labels: 📕 documentation, 🧑🏻‍💻 상수, 🧑🏻‍💻 현길, 🧑🏻‍💻 동훈

#56 211106 v1.0.0
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  src/.eslintrc.json
  src/.gitignore
  src/.prettierrc.json
  src/app.js
  src/bin/www.js
  src/configs/db.js
  src/configs/index.js
  src/configs/secretKey.js
  src/controllers/itemController.js
  src/controllers/menuController.js
  src/controllers/tagController.js
  src/controllers/userController.js
  src/globals/index.js
  src/globals/responseMessage.js
  src/globals/routes.js
  src/globals/statusCode.js
  src/libs/encryption.js
  src/libs/jwt.js
  src/middlewares/auth.js
  src/models/index.js
  src/models/item.js
  src/models/menu.js
  src/models/tag.js
  src/models/user.js
  src/package.json
  src/routes/globalRouter.js
  src/routes/index.js
  src/routes/menuRouter.js
  src/routes/tagRouter.js
  src/routes/tokenRouter.js
  src/routes/userRouter.js
  src/services/itemService.js
  src/services/menuService.js
  src/services/tagService.js
  src/services/userService.js
  src/test/Menu/createMenu.test.js
  src/test/Menu/deleteMenu.test.js
  src/test/Menu/getMenu.test.js
  src/test/Menu/getMenuList.test.js
  src/test/Menu/putMenu.test.js
  src/test/Tag/deleteTag.test.js
  src/test/Tag/getTagList.test.js
  src/test/Tag/postTag.test.js
  src/test/Tag/putTag.test.js
  src/test/Token/postToken.test.js
  src/test/User/signup.test.js
  src/utils/errors/commonError.js
  src/utils/errors/errors.js
  src/utils/errors/menuError.js
  src/utils/errors/tagError.js
  src/utils/errors/userError.js
  src/utils/index.js
  src/utils/logger.js
  src/utils/resFormatter.js
Labels: 🧑🏻‍💻 2차 과제 팀
